version: "3.9"

services:
  simple-fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/dynamic/simple-fastapi-app
    working_dir: /dynamic/simple-fastapi-app
    ports:
      - 8000:8000
    command: >
      uvicorn main:app --reload --host=0.0.0.0 --port=8000
