apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-fastapi-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: simple-fastapi-app
  template:
    metadata:
      labels:
        app: simple-fastapi-app
      annotations:
        cloud.goole.com/neg: '{"ingress": true}'
    spec:
      containers:
      - name: simple-fastapi-app
        image: asia.gcr.io/easydeep-dev/simple-fastapi-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "1000Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-fastapi-app-service-ip
spec:
  selector:
    app: simple-fastapi-app
  ports:
  - port: 3200
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-fastapi-app-service-lb
spec:
  selector:
    app: simple-fastapi-app
  type: LoadBalancer
  ports:
  - port: 3100
    targetPort: 8000
    nodePort: 30002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: easydeep-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: my-frontend-config
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: simple-fastapi-app-service-ip
            port:
              number: 3200
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - dev-api.easydeep.ai
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: my-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT
